import { useState } from 'react'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import Layout from '../components/Layout.js'
import { createPagesBrowserClient } from "@supabase/auth-helpers-nextjs";
import supabase from "@/components/supabaseClient";

// this page is for the contact form
export default function Page() {
  const [message, setMessage] = useState(null)
  /**
   * Handles the form submission event.
   * 
   * @param {Event} e - The form submission event.
   * @returns {Promise<void>} - A promise that resolves when the form submission is complete.
   */
  const onSubmit = async function (e) {
    e.preventDefault() 
    const data = new FormData(e.target)
    
    // Insert form data into the 'contacts' table in the database
    const { error } = await supabase
      .from('contacts')
      .insert(Object.fromEntries(data), { returning: 'minimal' })
    
    if (error) {
      setMessage('Sorry, an unexpected error occurred.')
    } else {
      setMessage(
        <div>
          <h2 className="text-center mt-3">Confirmation</h2>
          <p>Thank you for contacting us. We will get back to you promptly.</p>
        </div>
      )
    }
  }

  return (
    <Layout
      title="Contacts"
      description="Generated by create next app"
    >
      {/* Form to contact us */}
      <form className="grid grid-cols-1 gap-5 lg:w-full mx-auto" onSubmit={onSubmit}>
        <div className="w-full p-8 rounded-2xl shadow-2xl dark:bg-gray-800">
          <div className="flex">
            <h1 className="font-bold uppercase text-5xl dark:text-white">Send us a <br /> message</h1>
          </div>
          <div className="grid grid-cols-1 gap-5 md:grid-cols-2 mt-5">
            <input
              className="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
              type="text" placeholder="First Name*"
            />
            <input
              className="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
              type="text" placeholder="Last Name*"
            />
            <input
              className="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
              type="email" placeholder="Email*"
            />
            <input
              className="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
              type="number" placeholder="Phone*"
            />
          </div>
          <div className="my-4">
            <textarea
              placeholder="Message*"
              className="w-full h-32 bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
            ></textarea>
          </div>
          <div className="my-2 w-full lg:w-full">
            
            <button // Submit button
              className="uppercase text-sm font-bold tracking-wide bg-red-600 text-gray-100 p-3 rounded-lg w-full 
                        focus:outline-none focus:shadow-outline"
            >
              Send Message
            </button>

          </div>
        </div>
      </form>
      {/* Display the message if there is one */}
      {message &&
        <div
          aria-label="Overflow below the drawer dialog" 
          className="fixed inset-0 bg-black/80 flex items-center justify-center"
          onClick={() => setMessage(null)} // Hide the message when the user clicks on the overlay
          role="dialog" // A dialog is a window overlaid on either the primary window or another dialog window
        >
          <div
            aria-label="Alert pane"
            className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
          >
            {message}
          </div>
        </div>
      }
    </Layout>
  )
}